export const CATEGORIES = [
  {
    id: "incident",
    label: "Incidents",
    icon: "🚨",
    mode: "NOW",
    image: "emergency lights police response city night",
  },
  {
    id: "alert",
    label: "Alerts",
    icon: "📡",
    mode: "NOW",
    image: "warning alert emergency siren",
  },
  {
    id: "event",
    label: "Events",
    icon: "📅",
    mode: "BLOB",
    image: "community festival crowd outdoor event",
  },
  {
    id: "post",
    label: "Community",
    icon: "💬",
    mode: "BLOB",
    image: "community meeting diverse group discussion",
  },
  {
    id: "business",
    label: "Business & Services",
    icon: "🏪",
    mode: "BLOB",
    image: "small business shop front street",
  },
  {
    id: "transport",
    label: "Transport",
    icon: "🚦",
    mode: "NOW",
    image: "city traffic tram urban transport",
  },
  {
    id: "environment",
    label: "Environment",
    icon: "🌿",
    mode: "NOW",
    image: "park nature urban green environment",
  },
  {
    id: "request",
    label: "Requests",
    icon: "🛠️",
    mode: "NOW",
    image: "person asking for help service request",
  },
  {
    id: "feature",
    label: "Feature Requests",
    icon: "💡",
    mode: "BLOB",
    image: "lightbulb idea innovation concept",
  },
];