{
  id: "iview",
  title: "iVIEW",
  variant: "modes",
  items: [
    {
      id: "iview-now",
      label: "NOW",
      icon: "⚡",
      type: "mode",
      path: "/communityplus",
      mode: "NOW",
    },
    {
      id: "iview-news",
      label: "News",
      icon: "📰",
      type: "mode",
      path: "/communityplus",
      mode: "NEWS",
    },
    {
      id: "iview-blob",
      label: "BLOB",
      icon: "🧠",
      type: "mode",
      path: "/communityplus",
      mode: "BLOB",
    },
    {
      id: "iview-incidents",
      label: "Incidents",
      icon: "🚨",
      type: "mode",
      path: "/communityplus",
      mode: "INCIDENTS",
    },
    {
      id: "iview-events",
      label: "Events",
      icon: "📅",
      type: "mode",
      path: "/communityplus",
      mode: "EVENTS",
    },
    {
      id: "iview-beacon",
      label: "Beacon",
      icon: "📡",
      type: "mode",
      path: "/communityplus",
      mode: "BEACON",
    },
  ],
}