export const Capabilities = {

  CREATE_SIGNAL:
    "CREATE_SIGNAL",

  MODERATE_SIGNALS:
    "MODERATE_SIGNALS",

  MANAGE_LOCATION:
    "MANAGE_LOCATION",

  MANAGE_ORGANIZATION:
    "MANAGE_ORGANIZATION",

};